# Generated by Django 4.2.3 on 2023-07-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eve_id", models.PositiveIntegerField(blank=True, db_index=True)),
                ("name", models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Constellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eve_id",
                    models.PositiveIntegerField(db_index=True, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=250)),
                ("region_eve_id", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eve_id",
                    models.PositiveIntegerField(db_index=True, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=250)),
                (
                    "trade_rout",
                    models.CharField(
                        choices=[
                            ("hi_sec", "hi security"),
                            ("low_sec", "low security"),
                            ("null_sec", "null security"),
                        ],
                        default="null_sec",
                        max_length=250,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eve_id",
                    models.PositiveIntegerField(db_index=True, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=250)),
                (
                    "security_status",
                    models.DecimalField(decimal_places=1, max_digits=3, null=True),
                ),
                ("constellation_eve_id", models.PositiveIntegerField(null=True)),
                (
                    "constellation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system",
                        to="universe.constellation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eve_id", models.PositiveIntegerField(blank=True, db_index=True)),
                ("name", models.CharField(blank=True, max_length=250)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="universe.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="constellation",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constellation",
                to="universe.region",
            ),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eve_id",
                    models.PositiveIntegerField(
                        db_index=True, unique=True, verbose_name="EVE ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=250, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
                (
                    "packaged_volume",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                        verbose_name="Packaged volume",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                        verbose_name="Volume",
                    ),
                ),
                (
                    "market_group_id",
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name="Market ID"
                    ),
                ),
                (
                    "adjusted_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        null=True,
                        verbose_name="Adjusted price",
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        null=True,
                        verbose_name="Average price",
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(default="", max_length=250, verbose_name="icon"),
                ),
                (
                    "render_url",
                    models.URLField(default="", max_length=250, verbose_name="picture"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="universe.group",
                        verbose_name="Group",
                    ),
                ),
            ],
        ),
    ]
