# Generated by Django 4.2.3 on 2023-07-07 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("universe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constellation",
            name="region_eve_id",
        ),
        migrations.RemoveField(
            model_name="solarsystem",
            name="constellation_eve_id",
        ),
        migrations.AlterField(
            model_name="solarsystem",
            name="constellation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="systems",
                to="universe.constellation",
            ),
        ),
    ]
