# Generated by Django 4.2.3 on 2023-07-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("universe", "0002_remove_constellation_region_eve_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constellation",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constellations",
                to="universe.region",
            ),
        ),
    ]
