# Generated by Django 4.2.3 on 2023-07-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("universe", "0003_alter_constellation_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="constellation",
            name="id",
        ),
        migrations.RemoveField(
            model_name="region",
            name="id",
        ),
        migrations.RemoveField(
            model_name="solarsystem",
            name="id",
        ),
        migrations.AlterField(
            model_name="constellation",
            name="eve_id",
            field=models.PositiveIntegerField(
                default=1, editable=False, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="region",
            name="eve_id",
            field=models.PositiveIntegerField(
                default=1, editable=False, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="solarsystem",
            name="eve_id",
            field=models.PositiveIntegerField(
                default=1, editable=False, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
