# Generated by Django 4.2.3 on 2023-07-09 02:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "universe",
            "0005_remove_article_id_remove_category_id_remove_group_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="market_group_id",
        ),
    ]
