# Generated by Django 4.2.3 on 2023-07-10 13:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "Additional info",
                "verbose_name_plural": "Additional info",
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="refresh_token",
        ),
        migrations.AlterField(
            model_name="news",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
