# Generated by Django 4.2.3 on 2023-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pilot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketorder",
            name="article",
        ),
        migrations.RemoveField(
            model_name="marketorder",
            name="location",
        ),
        migrations.RemoveField(
            model_name="marketorder",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="marketorder",
            name="region",
        ),
        migrations.RemoveField(
            model_name="location",
            name="id",
        ),
        migrations.AlterField(
            model_name="location",
            name="eve_id",
            field=models.BigIntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="Character",
        ),
        migrations.DeleteModel(
            name="Corporation",
        ),
        migrations.DeleteModel(
            name="MarketOrder",
        ),
    ]
